"""add notification

Revision ID: 0b70d0dfdfab
Revises: 8c978adc6003
Create Date: 2025-06-15 18:23:50.406721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b70d0dfdfab'
down_revision: Union[str, None] = '8c978adc6003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('timeline_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_type_id'], ['timeline_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('send_at >= CURRENT_TIMESTAMP', name='send_at_not_in_past'),
    sa.ForeignKeyConstraint(['event_id'], ['timeline_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['notification_subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_notification')
    op.drop_table('notification_subscription')
    # ### end Alembic commands ###
