"""creation of data on educational areas

Revision ID: 5d57479a685f
Revises: 745c40bb8acb
Create Date: 2025-05-19 12:41:44.947733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d57479a685f'
down_revision: Union[str, None] = '745c40bb8acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('education_level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_duration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('years', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_form',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('timeline_event_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('timeline_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('education_level_id', sa.Integer(), nullable=False),
    sa.Column('study_form_id', sa.Integer(), nullable=False),
    sa.Column('study_duration_id', sa.Integer(), nullable=False),
    sa.Column('budget_places', sa.Integer(), nullable=True),
    sa.Column('target_places', sa.Integer(), nullable=True),
    sa.Column('quota_places', sa.Integer(), nullable=True),
    sa.Column('special_quota_places', sa.Integer(), nullable=True),
    sa.Column('paid_places', sa.Integer(), nullable=True),
    sa.Column('program_info', sa.Text(), nullable=True),
    sa.Column('career_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_level.id'], ),
    sa.ForeignKeyConstraint(['study_duration_id'], ['study_duration.id'], ),
    sa.ForeignKeyConstraint(['study_form_id'], ['study_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_contest_exam',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('contest_type_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contest_type_id'], ['contest_type.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_timeline_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['timeline_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.Column('budget_places', sa.String(), nullable=True),
    sa.Column('target_places', sa.String(), nullable=True),
    sa.Column('quota_places', sa.String(), nullable=True),
    sa.Column('paid_places', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('binding_id', sa.Integer(), nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['binding_id'], ['program_timeline_binding.id'], ),
    sa.ForeignKeyConstraint(['name_id'], ['timeline_event_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_event')
    op.drop_table('score_stat')
    op.drop_table('program_timeline_binding')
    op.drop_table('program_contest_exam')
    op.drop_table('program')
    op.drop_table('timeline_type')
    op.drop_table('timeline_event_name')
    op.drop_table('subject')
    op.drop_table('study_form')
    op.drop_table('study_duration')
    op.drop_table('education_level')
    op.drop_table('contest_type')
    # ### end Alembic commands ###
