"""add index to ProgramContestExam

Revision ID: 913e018ed317
Revises: 0c00a200f241
Create Date: 2025-06-03 10:09:23.742100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913e018ed317'
down_revision: Union[str, None] = '0c00a200f241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_pce_program_contest', 'program_contest_exam', ['program_id', 'contest_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pce_program_contest', table_name='program_contest_exam')
    # ### end Alembic commands ###
