name: Run tests

on:
  push:
  pull_request:



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create dummy .env file
        run: echo "" > .env

      - name: Create dummy .env.vector_db file
        run: echo "" > .env.vector_db
      
      - name: Build test-runner with cache
        uses: docker/build-push-action@v6
        with:
          context: .                       
          file: ./Dockerfile              
          build-args: |
            REQUIREMENTS=requirements-test.txt  
          tags: vyatsu_applicant_bot-test-runner:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from test-runner --no-build test-runner test-db test-bot_redis
  
    
      - name: Show logs if failed
        if: failure()
        run: |
          echo "===== test-runner logs ====="
          docker compose logs test-runner
          